# Generated by Django 3.1 on 2020-08-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200829_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='customer',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='strawberry.jpg', null=True, upload_to='product_images'),
        ),
    ]
