# Generated by Django 3.0.8 on 2020-09-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200829_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='date_odded',
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.IntegerField(null=True),
        ),
    ]
