# Generated by Django 3.1 on 2020-09-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_carouselslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_slides'),
        ),
    ]
