# Generated by Django 3.1 on 2020-09-12 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200910_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='category',
        ),
    ]
